/// Flutter icons GatraBaliIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GatraBaliIcons
///      fonts:
///       - asset: fonts/GatraBaliIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GatraBaliIcons {
  GatraBaliIcons._();

  static const _kFontFam = 'GatraBaliIcons';

  static const IconData balebengong = const IconData(0xe800, fontFamily: _kFontFam);
}
